/* Generator for emu2413_tables.h.
 *
 * This links against the real emu2413 implementation, builds an OPLL at the
 * fixed NES master clock (3579545 Hz, the only clock QuickNES ever uses), and
 * dumps every transcendental-derived table verbatim. The emitted values are
 * therefore bit-identical to what the floating-point init path produces on
 * this reference build, and become the canonical deterministic source.
 *
 * Rebuild only when a table formula or a tuning constant changes:
 *   g++ -DEMU2413_REGEN_TABLES -I.. -o gen gen_emu2413_tables.cpp ../emu2413.cpp
 *   ./gen > ../emu2413_tables.h
 *
 * (The -DEMU2413_REGEN_TABLES flag forces emu2413.cpp to compile the float
 *  builders rather than the baked path, so the generator can observe them.)
 */
#include <cstdio>
#include "emu2413.h"

static void dump_u16(const char* name, const e_uint16* p, int n)
{
	std::printf("static const e_uint16 %s[%d] = {\n", name, n);
	for (int i = 0; i < n; i++)
		std::printf("%u,%s", (unsigned)p[i], (i % 12 == 11) ? "\n" : " ");
	std::printf("\n};\n\n");
}

static void dump_i16(const char* name, const e_int16* p, int n)
{
	std::printf("static const e_int16 %s[%d] = {\n", name, n);
	for (int i = 0; i < n; i++)
		std::printf("%d,%s", (int)p[i], (i % 12 == 11) ? "\n" : " ");
	std::printf("\n};\n\n");
}

static void dump_i32(const char* name, const e_int32* p, int n)
{
	std::printf("static const e_int32 %s[%d] = {\n", name, n);
	for (int i = 0; i < n; i++)
		std::printf("%d,%s", (int)p[i], (i % 10 == 9) ? "\n" : " ");
	std::printf("\n};\n\n");
}

static void dump_u32(const char* name, const e_uint32* p, int n)
{
	std::printf("static const e_uint32 %s[%d] = {\n", name, n);
	for (int i = 0; i < n; i++)
		std::printf("%uu,%s", (unsigned)p[i], (i % 10 == 9) ? "\n" : " ");
	std::printf("\n};\n\n");
}

int main(void)
{
	OPLL* o = OPLL_new(3579545);

	std::printf("/* Auto-generated by tools/gen_emu2413_tables.cpp. Do not edit by hand.\n");
	std::printf(" * Baked at the fixed NES OPLL clock (3579545 Hz). Regenerate via the\n");
	std::printf(" * command in that file if any table formula or tuning constant changes. */\n");
	std::printf("#ifndef EMU2413_TABLES_H\n#define EMU2413_TABLES_H\n\n");

	dump_u16("baked_AR_ADJUST_TABLE", o->AR_ADJUST_TABLE, 1 << EG_BITS);
	dump_i16("baked_DB2LIN_TABLE",    o->DB2LIN_TABLE,    (DB_MUTE + DB_MUTE) * 2);
	dump_u16("baked_fullsintable",    o->fullsintable,    PG_WIDTH);
	dump_u16("baked_halfsintable",    o->halfsintable,    PG_WIDTH);
	dump_i32("baked_pmtable",         o->pmtable,         PM_PG_WIDTH);
	dump_i32("baked_amtable",         o->amtable,         AM_PG_WIDTH);
	dump_u32("baked_dphaseARTable",   &o->dphaseARTable[0][0], 16 * 16);
	dump_u32("baked_dphaseDRTable",   &o->dphaseDRTable[0][0], 16 * 16);
	dump_u32("baked_tllTable",        &o->tllTable[0][0][0][0], 16 * 8 * (1 << TL_BITS) * 4);

	std::printf("static const e_uint32 baked_pm_dphase = %uu;\n", (unsigned)o->pm_dphase);
	std::printf("static const e_uint32 baked_am_dphase = %uu;\n\n", (unsigned)o->am_dphase);

	std::printf("#endif /* EMU2413_TABLES_H */\n");

	OPLL_delete(o);
	return 0;
}
