/* Generator for nes_nonlin_table.h.
 *
 * The Nes_Nonlinearizer DAC curve is a fixed function of compile-time
 * constants (no sample rate, no EQ, no runtime parameter), so it bakes to a
 * single deterministic table. The formula here is the exact one from
 * Nes_Nonlinearizer::Nes_Nonlinearizer(); keep the two in sync (the ctor's
 * regen path compiles the same code, guarded by NES_NONLIN_REGEN).
 *
 * Regenerate:
 *   g++ -O2 -o gen gen_nes_nonlin_table.cpp && ./gen > ../nes_nonlin_table.h
 */
#include <cstdio>
#include <cstdint>

enum { table_bits = 11 };
enum { table_size = 1 << table_bits };
static double nonlinear_tnd_gain(void) { return 0.75; }

int main(void)
{
	int16_t table[table_size];

	float const gain = 0x7fff * 1.3f;
	int const range = (int) (table_size * nonlinear_tnd_gain());
	for (int i = 0; i < table_size; i++)
	{
		int const offset = table_size - range;
		int j = i - offset;
		float n = 202.0f / (range - 1) * j;
		float d = 0;
		if (n)
			d = gain * 163.67f / (24329.0f / n + 100.0f);
		int out = (int) d;
		table[j & (table_size - 1)] = (int16_t) out;
	}

	std::printf("/* Auto-generated by tools/gen_nes_nonlin_table.cpp. Do not edit by hand. */\n");
	std::printf("#ifndef NES_NONLIN_TABLE_H\n#define NES_NONLIN_TABLE_H\n\n");
	std::printf("static const int16_t baked_nonlin_table[%d] = {\n", table_size);
	for (int i = 0; i < table_size; i++)
		std::printf("%d,%s", (int) table[i], (i % 12 == 11) ? "\n" : " ");
	std::printf("\n};\n\n#endif\n");
	return 0;
}
