/* Generator for blip_kernels.h.
 *
 * Drives the REAL Blip_Synth_::treble_eq (float path, incl. adjust_impulse) for
 * every (quality, EQ preset, sample rate) combo QuickNES can request, and dumps
 * the resulting base kernel (kernel_unit == 32768, pre-volume). The emitted
 * values are therefore bit-identical to what treble_eq computes on this
 * reference build, and become the deterministic source for all platforms.
 *
 * Regenerate (must define BLIP_REGEN_KERNELS so treble_eq uses the float path
 * and the read accessors are exposed):
 *   g++ -O2 -DBLIP_REGEN_KERNELS -I.. -o gen gen_blip_kernels.cpp \
 *       ../Blip_Buffer.cpp && ./gen > ../blip_kernels.h
 */
#include <cstdio>
#include "Blip_Buffer.h"

struct Eq { const char* name; double treble; long rolloff; };
static Eq   eqs[6]   = { {"nes",-1.0,80}, {"famicom",-15.0,80}, {"tv",-12.0,180},
                         {"flat",0.0,1}, {"crisp",5.0,1}, {"tinny",-47.0,2000} };
static long rates[4] = { 32000, 44100, 48000, 96000 };

template<int Q>
static void dump_quality(void)
{
	for (int e = 0; e < 6; e++)
	for (int r = 0; r < 4; r++)
	{
		Blip_Synth<Q,1> synth;                     /* range is irrelevant to the kernel */
		blip_eq_t eq( eqs[e].treble, eqs[e].rolloff, rates[r] );
		synth.treble_eq( eq );                     /* volume_unit_==0 -> base kernel */

		short const* imp = synth.regen_impulses();
		int          n   = synth.regen_size();
		std::printf("/* q=%d eq=%s rate=%ld */\n", Q, eqs[e].name, rates[r]);
		std::printf("static const short bk_q%d_e%d_r%d[%d] = {\n", Q, e, r, n);
		for (int i = 0; i < n; i++)
			std::printf("%d,%s", (int)imp[i], (i % 12 == 11) ? "\n" : " ");
		std::printf("\n};\n");
	}
}

int main(void)
{
	std::printf("/* Auto-generated by tools/gen_blip_kernels.cpp. Do not edit by hand.\n");
	std::printf(" * Baked Blip synth base kernels for QuickNES's fixed EQ x rate x quality\n");
	std::printf(" * space. Regenerate if an EQ preset, supported rate, or quality changes. */\n");
	std::printf("#ifndef BLIP_KERNELS_H\n#define BLIP_KERNELS_H\n\n");

	dump_quality<8>();
	dump_quality<12>();

	/* Lookup dispatch: match on (width==quality, treble, rolloff, sample_rate).
	 * Returns the kernel pointer and length, or NULL on an off-menu combo. */
	std::printf("\nstatic const short* blip_lookup_kernel(int width, double treble,\n");
	std::printf("                                       long rolloff, long rate, int* out_n)\n{\n");
	const char* qn[2] = { "8", "12" };
	int         qv[2] = { 8, 12 };
	for (int qi = 0; qi < 2; qi++)
	{
		std::printf("  if (width == %d) {\n", qv[qi]);
		for (int e = 0; e < 6; e++)
		for (int r = 0; r < 4; r++)
		{
			std::printf("    if (treble == %.1f && rolloff == %ld && rate == %ld) { *out_n = (int)(sizeof bk_q%s_e%d_r%d/sizeof(short)); return bk_q%s_e%d_r%d; }\n",
				eqs[e].treble, eqs[e].rolloff, rates[r], qn[qi], e, r, qn[qi], e, r);
		}
		std::printf("  }\n");
	}
	std::printf("  (void)treble; (void)rolloff; (void)rate; *out_n = 0; return 0;\n}\n\n");

	std::printf("#endif /* BLIP_KERNELS_H */\n");
	return 0;
}
